server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    password: 'password'
    url: jdbc:postgresql://localhost:5433/customer_db
    username: 'app_user'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true